/**
 * @fileoverview gRPC-Web generated client stub for marble
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.2
// source: aggregates.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as aggregates_pb from './aggregates_pb'; // proto import: "aggregates.proto"


export class AggregatesServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetAggregate = new grpcWeb.MethodDescriptor(
    '/marble.AggregatesService/GetAggregate',
    grpcWeb.MethodType.UNARY,
    aggregates_pb.AggregatesRequest,
    aggregates_pb.AggregatesResponse,
    (request: aggregates_pb.AggregatesRequest) => {
      return request.serializeBinary();
    },
    aggregates_pb.AggregatesResponse.deserializeBinary
  );

  getAggregate(
    request: aggregates_pb.AggregatesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<aggregates_pb.AggregatesResponse>;

  getAggregate(
    request: aggregates_pb.AggregatesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: aggregates_pb.AggregatesResponse) => void): grpcWeb.ClientReadableStream<aggregates_pb.AggregatesResponse>;

  getAggregate(
    request: aggregates_pb.AggregatesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: aggregates_pb.AggregatesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/marble.AggregatesService/GetAggregate',
        request,
        metadata || {},
        this.methodDescriptorGetAggregate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/marble.AggregatesService/GetAggregate',
    request,
    metadata || {},
    this.methodDescriptorGetAggregate);
  }

  methodDescriptorWatchAggregates = new grpcWeb.MethodDescriptor(
    '/marble.AggregatesService/WatchAggregates',
    grpcWeb.MethodType.SERVER_STREAMING,
    aggregates_pb.AggregatesStreamRequest,
    aggregates_pb.AggregatesUpdate,
    (request: aggregates_pb.AggregatesStreamRequest) => {
      return request.serializeBinary();
    },
    aggregates_pb.AggregatesUpdate.deserializeBinary
  );

  watchAggregates(
    request: aggregates_pb.AggregatesStreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<aggregates_pb.AggregatesUpdate> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/marble.AggregatesService/WatchAggregates',
      request,
      metadata || {},
      this.methodDescriptorWatchAggregates);
  }

}

